<a href="https://colab.research.google.com/github/22104071/Financial-Transaction-Data-Engineering-/blob/main/SQL_Ingestion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 661.1 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [42]:
!service mysql status

 * MySQL is stopped.

In [43]:
!ps aux | grep mysql

root       26552  0.0  0.0   7372  3404 ?        S    10:04   0:00 /bin/bash -c ps aux | grep mysql
root       26554  0.0  0.0   6480  2552 ?        S    10:04   0:00 grep mysql

In [46]:
!service mysql start
!service mysql status

 * Starting MySQL database server mysqld
   ...done.
 * /usr/bin/mysqladmin  Ver 8.0.46-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))
Copyright (c) 2000, 2026, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Server version		8.0.46-0ubuntu0.22.04.2
Protocol version	10
Connection		Localhost via UNIX socket
UNIX socket		/var/run/mysqld/mysqld.sock
Uptime:			45 sec

Threads: 2  Questions: 14  Slow queries: 0  Opens: 119  Flush tables: 3  Open tables: 38  Queries per second avg: 0.311

In [47]:
MYSQL_DB = "fraud_detection"

In [48]:
!mysql -u root -e "CREATE DATABASE fraud_detection;"

In [49]:
!mysql -u root -e "SHOW DATABASES;"

+--------------------+
| Database           |
+--------------------+
| fraud_detection    |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+

In [50]:
!pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.2.0)

In [56]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root@localhost/fraud_detection?unix_socket=/var/run/mysqld/mysqld.sock"
)

with engine.connect() as conn:
    print("Connected Successfully")

Connected Successfully

In [57]:
!mysql -u root -e "SELECT user, host, plugin FROM mysql.user;"

+------------------+-----------+-----------------------+
| user             | host      | plugin                |
+------------------+-----------+-----------------------+
| debian-sys-maint | localhost | caching_sha2_password |
| mysql.infoschema | localhost | caching_sha2_password |
| mysql.session    | localhost | caching_sha2_password |
| mysql.sys        | localhost | caching_sha2_password |
| root             | localhost | auth_socket           |
+------------------+-----------+-----------------------+

In [60]:
!service mysql start

 * Starting MySQL database server mysqld
   ...done.

In [ ]:
import pandas as pd

pd.read_sql(
    "SHOW TABLES;",
    engine
)

In [63]:
customers = pd.read_csv(
    "/content/customers_clean.csv"
)

transactions = pd.read_csv(
    "/content/transactions_clean.csv"
)

master = pd.read_csv(
    "/content/master_dataset.csv"
)

In [64]:
print(customers.shape)
print(transactions.shape)
print(master.shape)

(169, 8)
(6666, 11)
(6666, 21)

In [67]:
print(type(customers))
print(customers.shape)
customers.head()

<class 'pandas.core.frame.DataFrame'>
(169, 8)

,dob,city,state,job,customer_id,account_type,credit_score,account_age_years
0,1978-06-21,Orient,WA,Special educational needs teacher,CUST00001,Premium,633,3
1,1962-01-19,Malad City,ID,Nature conservation officer,CUST00002,Savings,783,12
2,1945-12-21,Grenada,CA,Systems analyst,CUST00003,Premium,527,9
3,1967-08-30,High Rolls Mountain Park,NM,Naval architect,CUST00004,Premium,607,5
4,1967-08-02,Freedom,WY,"Education officer, museum",CUST00005,Savings,543,8

In [68]:
customers.columns.tolist()

['dob',
 'city',
 'state',
 'job',
 'customer_id',
 'account_type',
 'credit_score',
 'account_age_years']

In [69]:
customers.columns = (
    customers.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [70]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   dob                169 non-null    object
 1   city               169 non-null    object
 2   state              169 non-null    object
 3   job                169 non-null    object
 4   customer_id        169 non-null    object
 5   account_type       169 non-null    object
 6   credit_score       169 non-null    int64
 7   account_age_years  169 non-null    int64
dtypes: int64(2), object(6)
memory usage: 10.7+ KB

In [71]:
customers['dob'] = pd.to_datetime(
    customers['dob'],
    errors='coerce'
)

In [72]:
try:
    customers.to_sql(
        "customers",
        engine,
        if_exists="replace",
        index=False
    )
    print("Success")
except Exception as e:
    print(e)

(pymysql.err.OperationalError) (1698, "Access denied for user 'root'@'localhost'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [74]:
print(engine.url)

mysql+pymysql://root:***@127.0.0.1:3306/fraud_detection

In [76]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root@localhost/fraud_detection?unix_socket=/var/run/mysqld/mysqld.sock"
)

with engine.connect() as conn:
    print("Connection OK")

Connection OK

In [77]:
print(engine.url)

mysql+pymysql://root@localhost/fraud_detection?unix_socket=%2Fvar%2Frun%2Fmysqld%2Fmysqld.sock

In [78]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS test_table(
            id INT PRIMARY KEY
        )
    """))

print("Table Created")

Table Created

In [79]:
!mysql -u root -e "SHOW GRANTS FOR 'root'@'localhost';"

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for root@localhost                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, FILE, REFERENCES, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER, CREATE TABLESPACE, CREATE ROLE, DROP ROLE ON *.* TO `root`@`localhost` WITH GRANT OPTION                                                                                                                                                                                                                                                                                                                                                                                     |
| GRANT APPLICATION_PASSWORD_ADMIN,AUDIT_ABORT_EXEMPT,AUDIT_ADMIN,AUTHENTICATION_POLICY_ADMIN,BACKUP_ADMIN,BINLOG_ADMIN,BINLOG_ENCRYPTION_ADMIN,CLONE_ADMIN,CONNECTION_ADMIN,ENCRYPTION_KEY_ADMIN,FIREWALL_EXEMPT,FLUSH_OPTIMIZER_COSTS,FLUSH_STATUS,FLUSH_TABLES,FLUSH_USER_RESOURCES,GROUP_REPLICATION_ADMIN,GROUP_REPLICATION_STREAM,INNODB_REDO_LOG_ARCHIVE,INNODB_REDO_LOG_ENABLE,PASSWORDLESS_USER_ADMIN,PERSIST_RO_VARIABLES_ADMIN,REPLICATION_APPLIER,REPLICATION_SLAVE_ADMIN,RESOURCE_GROUP_ADMIN,RESOURCE_GROUP_USER,ROLE_ADMIN,SENSITIVE_VARIABLES_OBSERVER,SERVICE_CONNECTION_ADMIN,SESSION_VARIABLES_ADMIN,SET_USER_ID,SHOW_ROUTINE,SYSTEM_USER,SYSTEM_VARIABLES_ADMIN,TABLE_ENCRYPTION_ADMIN,TELEMETRY_LOG_ADMIN,XA_RECOVER_ADMIN ON *.* TO `root`@`localhost` WITH GRANT OPTION |
| GRANT PROXY ON ``@`` TO `root`@`localhost` WITH GRANT OPTION                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

In [84]:

engine = create_engine(
    "mysql+pymysql://fraud_user:fraud123@localhost/fraud_detection?unix_socket=/var/run/mysqld/mysqld.sock"
)

In [85]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE test_table (
            id INT PRIMARY KEY
        )
    """))

print("Success")

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'fraud_user'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [86]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   dob                169 non-null    datetime64[ns]
 1   city               169 non-null    object
 2   state              169 non-null    object
 3   job                169 non-null    object
 4   customer_id        169 non-null    object
 5   account_type       169 non-null    object
 6   credit_score       169 non-null    int64
 7   account_age_years  169 non-null    int64
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 10.7+ KB

In [87]:
customers.head()

,dob,city,state,job,customer_id,account_type,credit_score,account_age_years
0,1978-06-21,Orient,WA,Special educational needs teacher,CUST00001,Premium,633,3
1,1962-01-19,Malad City,ID,Nature conservation officer,CUST00002,Savings,783,12
2,1945-12-21,Grenada,CA,Systems analyst,CUST00003,Premium,527,9
3,1967-08-30,High Rolls Mountain Park,NM,Naval architect,CUST00004,Premium,607,5
4,1967-08-02,Freedom,WY,"Education officer, museum",CUST00005,Savings,543,8

In [89]:
customers['dob'] = customers['dob'].astype(str)

In [92]:
print(engine.url)

mysql+pymysql://fraud_user:***@localhost/fraud_detection?unix_socket=%2Fvar%2Frun%2Fmysqld%2Fmysqld.sock

In [93]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root@localhost/fraud_detection?unix_socket=/var/run/mysqld/mysqld.sock"
)

print(engine.url)

mysql+pymysql://root@localhost/fraud_detection?unix_socket=%2Fvar%2Frun%2Fmysqld%2Fmysqld.sock

In [94]:
import pandas as pd

test_df = pd.DataFrame({
    "id":[1,2,3],
    "name":["A","B","C"]
})

test_df.to_sql(
    "simple_test",
    engine,
    if_exists="replace",
    index=False
)

3

In [96]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root@localhost/fraud_detection?unix_socket=/var/run/mysqld/mysqld.sock"
)

In [97]:
customers.to_sql(
    "customers",
    engine,
    if_exists="replace",
    index=False
)

print("Customers table uploaded")

Customers table uploaded

In [98]:
pd.read_sql(
    "SELECT COUNT(*) FROM customers",
    engine
)

   COUNT(*)
0       169

In [99]:
transactions.to_sql(
    "transactions",
    engine,
    if_exists="replace",
    index=False
)

print("Transactions table uploaded")

Transactions table uploaded

In [100]:
pd.read_sql(
    "SELECT COUNT(*) FROM transactions",
    engine
)

   COUNT(*)
0      6666

In [101]:
pd.read_sql(
    "SHOW TABLES;",
    engine
)

  Tables_in_fraud_detection
0                 customers
1               simple_test
2                test_table
3              transactions

In [102]:
query = """
SELECT
    COUNT(*) AS total_transactions,
    SUM(is_fraud) AS fraud_transactions,
    ROUND(
        SUM(is_fraud)*100/COUNT(*),
        2
    ) AS fraud_rate
FROM transactions
"""

pd.read_sql(query, engine)

   total_transactions  fraud_transactions  fraud_rate
0                6666                63.0        0.95

In [103]:
query = """
SELECT
    category,
    COUNT(*) AS fraud_count
FROM transactions
WHERE is_fraud = 1
GROUP BY category
ORDER BY fraud_count DESC
"""

pd.read_sql(query, engine)

          category  fraud_count
0     shopping_net           15
1      grocery_pos           11
2     shopping_pos            7
3    gas_transport            6
4         misc_net            6
5      grocery_net            5
6    entertainment            4
7         misc_pos            2
8    personal_care            2
9   health_fitness            1
10       kids_pets            1
11     food_dining            1
12            home            1
13          travel            1

In [104]:
query = """
SELECT
    category,
    ROUND(AVG(amt),2) avg_amount
FROM transactions
GROUP BY category
ORDER BY avg_amount DESC
"""

pd.read_sql(query, engine)

          category  avg_amount
0      grocery_pos      124.77
1     shopping_net      116.23
2         misc_net       86.35
3           travel       81.00
4     shopping_pos       73.79
5    entertainment       66.07
6    gas_transport       63.30
7         misc_pos       58.70
8             home       57.17
9      grocery_net       56.51
10       kids_pets       56.48
11  health_fitness       54.54
12     food_dining       48.92
13   personal_care       48.31

In [105]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS predictions(
        prediction_id INT AUTO_INCREMENT PRIMARY KEY,
        transaction_id VARCHAR(50),
        prediction INT,
        fraud_probability FLOAT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """))

In [106]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS predictions(
        prediction_id INT AUTO_INCREMENT PRIMARY KEY,
        transaction_id VARCHAR(50),
        prediction INT,
        fraud_probability FLOAT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """))

In [107]:
pd.read_sql(
    "SHOW TABLES;",
    engine
)

  Tables_in_fraud_detection
0                 customers
1               predictions
2               simple_test
3                test_table
4              transactions

In [108]:
with engine.begin() as conn:
    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS engineered_features(
        transaction_id VARCHAR(50),
        customer_id VARCHAR(50),
        hour INT,
        age INT,
        weekend_flag INT,
        PRIMARY KEY(transaction_id)
    )
    """))

In [109]:
pd.read_sql(
    "SELECT * FROM customers LIMIT 5",
    engine
)

,dob,city,state,job,customer_id,account_type,credit_score,account_age_years
0,1978-06-21,Orient,WA,Special educational needs teacher,CUST00001,Premium,633,3
1,1962-01-19,Malad City,ID,Nature conservation officer,CUST00002,Savings,783,12
2,1945-12-21,Grenada,CA,Systems analyst,CUST00003,Premium,527,9
3,1967-08-30,High Rolls Mountain Park,NM,Naval architect,CUST00004,Premium,607,5
4,1967-08-02,Freedom,WY,"Education officer, museum",CUST00005,Savings,543,8

In [110]:
pd.read_sql(
    "SELECT * FROM transactions LIMIT 5",
    engine
)

,transaction_id,customer_id,trans_date_trans_time,merchant,category,amt,lat,long,merch_lat,merch_long,is_fraud
0,TXN0000001,CUST00001,2019-01-01 00:00:44,"Heller, Gutmann and Zieme",grocery_pos,107.23,48.8878,-118.2105,49.159047,-118.186462,0
1,TXN0000002,CUST00002,2019-01-01 00:00:51,Lind-Buckridge,entertainment,220.11,42.1808,-112.2620,43.150704,-112.154481,0
2,TXN0000003,CUST00003,2019-01-01 00:07:27,Kiehn Inc,grocery_pos,96.29,41.6125,-122.5258,41.657520,-122.230347,0
3,TXN0000004,CUST00004,2019-01-01 00:09:03,Beier-Hyatt,shopping_pos,7.77,32.9396,-105.8189,32.863258,-106.520205,0
4,TXN0000005,CUST00005,2019-01-01 00:21:32,Bruen-Yost,misc_pos,6.85,43.0172,-111.0292,43.753735,-111.454923,0